# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['exiur_cli.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'click',
        'click.shell_completion',
        'rich',
        'rich.console',
        'rich.table',
        'rich.text',
        'rich.markup',
        'rich.panel',
        'rich.progress',
        'rich.theme',
        'rich.style',
        'rich.highlighter',
        'rich.live',
        'rich.columns',
        'rich.pretty',
        'rich.syntax',
        'rich.tree',
        'rich.traceback',
        'pygments',
        'pygments.lexers',
        'pygments.styles',
        'markdown_it',
        'markdown_it.py',
        'mdurl',
        'certifi',
        'charset_normalizer',
        'idna',
        'urllib3',
        'requests',
        'exiur',
        'exiur.api',
        'exiur.config',
        'exiur.menu',
        'exiur.ui',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='exiur',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
